framework:
    secret: '%env(APP_SECRET)%'

    form:
        csrf_protection:
            enabled: true

    session: true

    trusted_proxies: '127.0.0.1'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto']
