security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: login

  firewalls:
    dev:
      pattern: ^/(_profiler|_wdt|assets|build)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      form_login:
        login_path: login
        check_path: login
        username_parameter: _login
        password_parameter: _password
        default_target_path: gestionnaire_burgers

      logout:
        path: logout
        target: home

  access_control:
    - { path: ^/$, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/gestionnaire, roles: ROLE_GESTIONNAIRE }
