# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Enregistre automatiquement les services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Alias Cloudinary
    App\Service\Cloudinary\CloudinaryServiceInterface:
        alias: App\Service\Cloudinary\CloudinaryService

    # Alias Burger
    App\Service\Burger\BurgerServiceInterface:
        alias: App\Service\Burger\BurgerService
